### ISSUE TITLE
Demo URL not working

### ISSUE THREAD

**Issue by karunainfotech** [hackolantern/govhack-vet-provider-map#4]
Hi Jackie,

The demo URL provided below is not working .
https://2017.hackerspace.govhack.org/content/vet-provider-map

Please provide updated URL with working demo of vetmap .

Thanks,
KK

**Comment by jumpinjackie** [comment]
This URL and this repository was only meant to stay up for the duration of the 2015 GovHack hackathon (nearly 3 years ago). Do whatever you want with the source code, but I have no intention of bringing the demo site back up.
