### ISSUE TITLE
Vet Map Error

### ISSUE THREAD

**Issue by karunainfotech** [hackolantern/govhack-vet-provider-map#5]
Hello..

We are tried to configure the  govhack-vet-provider-map  from repository path http://themapguyde.blogspot.in/search?q=vet

 i found few files are missing from repository . please fine the link below of Vet Map configuration in our server for the error details 
List of missing files i found 
1.  services folder in rest folder
2. Createmap.Json file

![vetmap](https://user-images.githubusercontent.com/34934938/35731882-60172f3e-083d-11e8-9d4d-feeae4193872.png)

**Comment by jumpinjackie** [comment]
Those "files" are provided by [mapguide-rest](https://github.com/jumpinjackie/mapguide-rest) which it doesn't look like you have actually installed
